### ISSUE TITLE
Code Refactoring

### ISSUE THREAD

**Issue by J-hoplin1** [J-hoplin1/Tython_Function#5]
## Issue
***
Refactoring code

### TODO List

- [x] Naming Convention 재정비 : Decorator, 함수 인자는 snake_case로 변경
- [x] colorprinte대신 colorama 오픈소스 활용해보기
- [ ] setup.py작성, poetry를 사용하여 의존성 관리
- [ ] Add linter
